
# Navigasi menu pada _data dan _include tidak bisa dijalankan. Belum tahu, cek pakai _config.yml

- name: Utama
  link: /
- name: Blog
  link: /blog.html
- name: Tentang
  link: /tentang.html
- name: "Apa itu?"
  link: /index..html

# Judul dan sebagainya

title: "IMLSHOR Indonesia"
description: "Akhirnya, bisa membuat website. Alhamdulillah"
include: /AmberRobocarPoliFX/*
