- name: Utama
  link: /
- name: Blog
  link: /blog.html
- name: Tentang
  link: /tentang.html
- name: "Apa itu?"
  link: /index..html

title: "IMLSHOR Indonesia"
description: "Akhirnya, bisa membuat website. Alhamdulillah"
include: /AmberRobocarPoliFX/*
